-- SPDX-License-Identifier: BSD-3-Clause
with Ada.Command_Line; with Interfaces.C;
with MC_Types; use MC_Types;
with MC_Runtime; with MC_Clock; with MC_Posix; with MC_Store; with MC_SHA256;
with Pkg_Conffile_Snapshot; with Pkg_Conffile_Transition;
with Test_Support; use Test_Support;
procedure Run_Conffile_Snapshot_Tests with SPARK_Mode => Off is
   package S renames Pkg_Conffile_Snapshot;
   use type Pkg_Conffile_Transition.File_Kind;
   use type Interfaces.C.int; use type Interfaces.C.long;
   Store, Closed_Store : MC_Store.Store; Value : S.Snapshot;
   Status : Outcome; Deadline : Counter;
   Root, FD : MC_Posix.FD := -1; Ignored : Interfaces.C.int;
   Config : aliased constant String := "na me-" & Character'Val (255) & Character'Val (0);
   Path : constant String := "/" & Config (Config'First .. Config'Last - 1);
   Original : aliased constant Bytes := (108, 111, 99, 97, 108);
   Changed : aliased constant Bytes := (111, 116, 104, 101, 114);
   Large : aliased constant Bytes (1 .. 131_077) := (others => 42);
   Read_Back : Bytes (1 .. 1024); Used : Natural; First_Meta : Digest;
   procedure Need (Label_Text : String) is
   begin Expect (Status = OK, Label_Text & Outcome'Image (Status)); end Need;
   procedure Capture is
   begin S.Capture (Store, Integer (Root), Path, 1024, Deadline, Value, Status); Need ("capture"); end Capture;
begin
   Expect (Ada.Command_Line.Argument_Count = 2, "private CAS and configuration root");
   MC_Runtime.Initialize (Status); Need ("runtime");
   MC_Clock.Boottime_Milliseconds (Deadline, Status); Need ("clock"); Deadline := Deadline + 30_000;
   MC_Store.Initialize (Ada.Command_Line.Argument (1), Store, Status); Need ("CAS");
   declare Name : aliased constant String := Ada.Command_Line.Argument (2) & Character'Val (0);
   begin Root := MC_Posix.Open (Name'Address, MC_Posix.O_PATH + MC_Posix.O_DIRECTORY + MC_Posix.O_CLOEXEC + MC_Posix.O_NOFOLLOW, 0); end;
   Expect (Root >= 0, "root descriptor");
   Capture;
   Expect (S.Current (Value).Kind = Pkg_Conffile_Transition.Missing and then S.Metadata (Value) /= Zero_Digest, "retained actual absence");
   S.Recheck (Store, Value, Deadline, Status); Need ("same absence");
   FD := MC_Posix.Openat (Root, Config'Address, MC_Posix.O_RDWR + MC_Posix.O_CREAT + MC_Posix.O_EXCL + MC_Posix.O_CLOEXEC, 8#600#);
   Expect (FD >= 0 and then MC_Posix.Write (FD, Original'Address, Original'Length) = Original'Length, "create local config");
   S.Recheck (Store, Value, Deadline, Status);
   Expect (Status = Stale and then S.Current (Value).Kind = Pkg_Conffile_Transition.Other and then S.Metadata (Value) = Zero_Digest, "creation invalidates absence and clears");
   Capture; First_Meta := S.Metadata (Value);
   Expect (S.Current (Value).Kind = Pkg_Conffile_Transition.Regular and then S.Current (Value).Content = MC_SHA256.Hash (Original), "actual local hash");
   MC_Store.Read_Object (Store, S.Current (Value).Content, Read_Back, Used, Status); Need ("retained local");
   Expect (Used = Original'Length and then Read_Back (1 .. Used) = Original, "exact preserved content");
   MC_Store.Read_Object (Store, First_Meta, Read_Back, Used, Status); Need ("retained attributes");
   Expect (Used > 8 and then Read_Back (1 .. 8) = Bytes'(78, 73, 65, 67, 79, 66, 83, 49), "versioned observation");
   S.Recheck (Store, Value, Deadline, Status); Need ("unchanged snapshot");
   Expect (MC_Posix.Lseek (FD, 0, 0) = 0 and then MC_Posix.Write (FD, Changed'Address, Changed'Length) = Changed'Length, "edit local config");
   S.Recheck (Store, Value, Deadline, Status); Expect (Status = Stale, "content changed");
   MC_Store.Read_Object (Store, MC_SHA256.Hash (Original), Read_Back, Used, Status); Need ("old content survives edit");
   Expect (Read_Back (1 .. Used) = Original, "immutable backup source");
   Capture; Expect (S.Metadata (Value) /= First_Meta, "fresh metadata identity");
   Expect (MC_Posix.Fchmod (FD, 8#640#) = 0, "change mode");
   S.Recheck (Store, Value, Deadline, Status); Expect (Status = Stale, "mode change invalidates");
   Capture; S.Recheck (Closed_Store, Value, Deadline, Status);
   Expect (Status = Invalid_Input and then S.Metadata (Value) = Zero_Digest, "requires same held CAS");
   Capture; S.Recheck (Store, Value, 0, Status);
   Expect (Status = Stale and then S.Metadata (Value) = Zero_Digest, "deadline invalidates");
   S.Capture (Store, Integer (Root), Path & Character'Val (0) & "tail", 1024, Deadline, Value, Status);
   Expect (Status = Invalid_Input and then S.Current (Value).Kind = Pkg_Conffile_Transition.Other, "embedded NUL not truncated");
   Expect (MC_Posix.Unlinkat (Root, Config'Address, 0) = 0, "remove test config");
   Capture; Expect (S.Current (Value).Kind = Pkg_Conffile_Transition.Missing, "deletion distinct from empty");
   Ignored := MC_Posix.Close (FD);
   FD := MC_Posix.Openat (Root, Config'Address, MC_Posix.O_RDWR + MC_Posix.O_CREAT + MC_Posix.O_EXCL + MC_Posix.O_CLOEXEC, 8#600#);
   Expect (FD >= 0, "create empty regular");
   S.Capture (Store, Integer (Root), Path, 0, Deadline, Value, Status); Need ("zero size capture");
   Expect (S.Current (Value).Kind = Pkg_Conffile_Transition.Regular and then S.Current (Value).Content = MC_SHA256.Hash (Bytes'(1 .. 0 => 0)), "empty regular has real digest");
   Expect (MC_Posix.Write (FD, Large'Address, Large'Length) = Large'Length, "multiple content chunks");
   S.Capture (Store, Integer (Root), Path, Large'Length, Deadline, Value, Status); Need ("stream content to CAS");
   Expect (S.Current (Value).Content = MC_SHA256.Hash (Large), "chunk boundaries preserve exact content");
   S.Recheck (Store, Value, Deadline, Status); Need ("large content recheck");
   Expect (MC_Posix.Unlinkat (Root, Config'Address, 0) = 0, "remove large fixture");
   S.Clear (Value); Ignored := MC_Posix.Close (FD); FD := -1;
   Ignored := MC_Posix.Close (Root); Root := -1; MC_Store.Close (Store); Report;
exception when others => S.Clear (Value); Ignored := MC_Posix.Close (FD); Ignored := MC_Posix.Close (Root); MC_Store.Close (Store); raise;
end Run_Conffile_Snapshot_Tests;
