# SPDX-License-Identifier: BSD-3-Clause
# Generated by assurance/ci/sync-component-ci.py.
# All component proofs share the guard's per-user lock. No unbounded fallback.
.PHONY: flow prove
flow: check-contract
	@command -v "$(GNATPROVE)" >/dev/null || { echo 'GNATprove missing; proof NOT RUN' >&2; exit 78; }
	mkdir -p build/proof-obj
	python3 ci/proof-guard.py -- "$(GNATPROVE)" -P proof.gpr -U --mode=flow --checks-as-errors=on --warnings=error
prove: check-contract
	@command -v "$(GNATPROVE)" >/dev/null || { echo 'GNATprove missing; proof NOT RUN' >&2; exit 78; }
	mkdir -p build/proof-obj
	python3 ci/proof-guard.py -- "$(GNATPROVE)" -P proof.gpr -U --mode=all --level=4 --checks-as-errors=on --warnings=error --proof-warnings=on --report=statistics
